#!/bin/sh

if [ "$(dpkg -l qmail-toaster)" != "" ] ; then
	echo
	echo "Mail server already use qmail-toaster"
	echo
	if ! [ "$1" == "--force" ] ; then
		exit
	fi
else
	echo
	echo "Mail server already use qmail from LxCenter"
	echo "Convert processing..."
	echo
fi

apt-get remove qmail* vpopmail* *-toaster exim* dovecot* postfix* -y
dpkg -r vpopmail
apt-get clean all
apt-get install qmail-toaster -y

sh /script/fix-qmail-assign
'rm' -f /etc/xinetd.d/*_lxa
chkconfig courier-imap off 2>/dev/null

'rm' -f /etc/rc.d/init.d/courier-imap

echo 'localhost' > /var/qmail/control/locals

sh /script/fixvpop
sh /script/cleanup

echo "Need reboot!"
echo