#!/bin/sh

kloxopath='/usr/local/lxlabs/kloxo'

apt-get -y -q install python2.7 python2.7-dev python-pip python-setuptools \
	python-virtualenv >/dev/null 2>&1

apt-get install -y -q python python-dev python-virtualenv >/dev/null 2>&1

apt-get remove -y -q python2.7-tools >/dev/null 2>&1

# these would be installed automaticly by the client but I prefer to do it myself
apt-get -y -q install gcc dialog libaugeas0 libssl-dev libffi-dev \
	ca-certificates >/dev/null 2>&1

# install let
apt-get -y -q install git >/dev/null 2>&1
cd ${kloxopath}
if [ -d ${kloxopath}/letsencrypt ] ; then
	'rm' -rf ${kloxopath}/letsencrypt >/dev/null 2>&1
	'rm' -rf /root/.local/share/letsencrypt >/dev/null 2>&1
fi

if [ -d ${kloxopath}/certbot ] ; then
	'rm' -rf ${kloxopath}/certbot >/dev/null 2>&1
	'rm' -rf /root/.local/share/certbot >/dev/null 2>&1
fi

wget https://github.com/certbot/certbot/archive/master.zip -O master.zip \
	--no-check-certificate >/dev/null 2>&1

unzip -oq master.zip >/dev/null 2>&1
'mv' -f certbot-master certbot >/dev/null 2>&1
'rm' -f master.zip >/dev/null 2>&1

ln -sf ${kloxopath}/certbot/letsencrypt-auto /usr/bin/letsencrypt-auto >/dev/null 2>&1
ln -sf ${kloxopath}/certbot/certbot-auto /usr/bin/certbot-auto >/dev/null 2>&1
ln -sf ${kloxopath}/certbot/py26reqs.txt /usr/bin/py26reqs.txt >/dev/null 2>&1

cronfile='/var/spool/cron/root'

'cp' -f ${kloxopath}/file/letsencrypt/letsencrypt-cron.sh \
	${kloxopath}/certbot/letsencrypt-cron.sh \
	>/dev/null 2>&1

if [ -f ${cronfile} ] ; then
	if [ "$(cat ${cronfile}|grep 'letsencrypt-cron.sh')" != "" ] ; then
		## MR -- remove old cron
		sed -i '/letsencrypt\-cron\.sh/d' ${cronfile}
	fi
fi

## MR -- use it because priority for acme.sh if exists
if [ ! -f /root/.acme.sh/acme.sh ] ; then
	if [ "$(cat ${cronfile}|grep 'acme-cron.sh')" != "" ] ; then
		## MR -- remove old cron
		sed -i '/acme\-cron\.sh/d' ${cronfile}
	fi
fi

sh /script/fix-cron-ssl

cd /

echo
${kloxopath}/certbot/letsencrypt-auto --version
echo