#!/bin/sh

echo "*** Installing 'rkhunter' ***"

if [ "$(dpkg -l rkhunter)" == "" ] ; then
	echo "* 'rkhunter' install processing"
	apt-get install tnef which gcc g++ zip unzip libcurl4-openssl-dev autoconf \
		automake make libtool libssl-dev pure-ftpd apt-protect \
		cron make libc6-dev net-snmp tmpwatch \
		rkhunter quota xinetd screen telnet ncdu sysstat net-tools \
		xz-utils p7zip-full rar unrar lxjailshell deltarpm
else
	echo "* 'rkhunter' already installed"
fi

echo "* Updating 'rkhunter'"
rkhunter --update

if [ -f /var/lib/rkhunter/db/rkhunter.dat ] ; then
	echo "* 'rkhunter.dat' file already exits"
else
	echo "* Running 'rkhunter --propupd' to creating 'rkhunter.dat'"
	rkhunter --propupd
fi
