#!/bin/sh

if [ "$1" == "httpd24" ] ; then
	if [ "$(rpm -qa httpd24u)" == "" ] ; then
		if [ "$(rpm -qa|grep 'httpd-')" == "" ] ; then
			echo
			echo "- Need select apache or proxy in 'Switch Programs'"
			echo
			exit
		else
			service httpd stop
			apt-get -y install apache2
			apt-get -y remove libapache2-mod-ssl libapache2-mod-rpaf libapache2-mod-ruid2 libapache2-mod-suphp libapache2-mod-fastcgi libapache2-mod-fcgid
			apt-get -y install libapache2-mod-ssl libapache2-mod-session libapache2-mod-suphp libapache2-mod-ruid2 libapache2-mod-fcgid libapache2-mod-fastcgi
			cp -f /opt/configs/apache/etc/conf/httpd24.conf /etc/httpd/conf/httpd.conf
			chkconfig httpd on

			echo
			echo "- Then, run 'sh /script/fixweb; sh /script/fixphp; sh /script/restart-web -y'"
			echo
			exit
		fi
	else
		echo
		echo "- httpd24 already installed"
		echo
		exit
	fi

	cat '' > /usr/local/lxlabs/kloxo/etc/flag/use_apache24.flg
elif [ "$1" == "httpd" ] ; then
	if [ "$(rpm -qa httpd)" == "" ] ; then
		if [ "$(rpm -qa|grep 'httpd24u-')" == "" ] ; then
			echo
			echo "- Need select apache or proxy in 'Switch Programs'"
			echo
			exit
		else
			service httpd stop
			apt-get -y install apache2
			apt-get -y remove libapache2-mod-ssl libapache2-mod-session libapache2-mod-suphp libapache2-mod-ruid2 libapache2-mod-fcgid libapache2-mod-fastcgi
			apt-get -y install libapache2-mod-ssl libapache2-mod-rpaf libapache2-mod-ruid2 libapache2-mod-suphp libapache2-mod-fastcgi libapache2-mod-fcgid
			cp -f /opt/configs/apache/etc/conf/httpd.conf /etc/httpd/conf/httpd.conf
			chkconfig httpd on

			echo
			echo "- Then, run 'sh /script/fixweb; sh /script/fixphp; sh /script/restart-web -y'"
			echo
			exit
		fi
	else
		echo
		echo "- httpd already installed"
		echo
		exit
	fi
	
	rm -f /usr/local/lxlabs/kloxo/etc/flag/use_apache24.flg
else
	echo
	echo "- Execute: '$0 httpd' or '$0 httpd24'"
	echo
fi

